# https://docs.microsoft.com/azure/devops/pipelines/yaml-schema

stages:
- stage: BuildStage
  displayName: Build stage
  jobs:
  - job: BuildJob
    displayName: Build job
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'windows-latest'
        windows:
          imageName: 'macOS-latest'
    pool:
      vmImage: $(imageName)
    workspace:
      clean: all

    steps:
    - task: UseDotNet@2
      displayName: Install .NET Core 3
      inputs:
        version: '3.0.x'

    - task: DotNetCoreCLI@2
      displayName: 'Install Cake'
      inputs:
        command: custom
        custom: tool
        arguments: 'install -g cake.tool'

    - task: DotNetCoreCLI@2
      displayName: 'Run Cake'
      inputs:
        command: custom
        custom: cake
        arguments: 'build.cake'

    - publish: '$(Build.Repository.LocalPath)/artifacts'
      displayName: Publish artifacts
      condition: eq(variables['imageName'], 'ubuntu-latest')
      artifact: 'packages'

- stage: PublishAlphaPackageStage
  displayName: Publish alpha package stage
  dependsOn: BuildStage
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  jobs:
  - job: PublishAlphaPackageJob
    displayName: Publish alpha package job
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: none

    - download: current
      displayName: Download artifacts
      artifact: 'packages'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'push'
        packagesToPush: '$(Pipeline.Workspace)/packages/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'pingct'